# Generated by Django 4.2.8 on 2023-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='context',
            field=models.TextField(default='{}', verbose_name='Контекст'),
        ),
    ]
