# Generated by Django 4.2.8 on 2023-12-18 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_travel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь ТГ', 'verbose_name_plural': 'Пользователи ТГ'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AddField(
            model_name='travel',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 12, 58, 45, 890147), verbose_name='Дата и время окончания выезда'),
        ),
        migrations.AddField(
            model_name='travel',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 12, 58, 45, 890147), verbose_name='Дата и время начала выезда'),
        ),
    ]
