# Generated by Django 4.2.8 on 2023-12-18 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_telegramuser_options_alter_travel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 15, 4, 47, 320508), verbose_name='Дата и время окончания выезда'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 15, 4, 47, 320508), verbose_name='Дата и время начала выезда'),
        ),
    ]
